### ISSUE TITLE
Can't publish cita-vm to crates.io

### ISSUE THREAD

**Issue by mohanson** [cryptape/cita-vm#34]
We used `https://github.com/paritytech/bn` as a dependency for implements pre-compiled contracts, but this baby havn't publish itself to crates.io, so, bad things happened

```
$ cargo publish
    Updating crates.io index
error: crates cannot be published to crates.io with dependencies sourced from a repository
either publish `bn` as its own crate on crates.io and specify a crates.io version as a dependency or pull it into this repository and specify it with a path and version
(crate `bn` has repository path `https://github.com/paritytech/bn`)
```

**Comment by ouwenkg** [comment]
Sad

**Comment by yejiayu** [comment]
So sad

**Comment by mohanson** [comment]
Since parity don't agree to publish the `bn` (https://github.com/paritytech/parity-ethereum/issues/10500)
 I forked this repo and publish it myself with name `parity-bn`

**Comment by mohanson** [comment]
I have rename it to 'lib-bn'
