### ISSUE TITLE
Why do I need to pass DB ownership to "State DB"

### ISSUE THREAD

**Issue by yejiayu** [cryptape/cita-vm#35]
In here should not let me pass DB ownership.

https://github.com/cryptape/cita-vm/blob/ca03031c0f4d741a3ae53d18d338b1747a0aa569/state/src/state.rs#L13-L32

I think should pass a `&mut B` and give it a lifetime.

like
```rust
pub fn new(db: &'db mut B)
```

**Comment by mohanson** [comment]
To be honest, @ouwenkg and I wrote the statedb by reference part of parity's code, thus, https://github.com/paritytech/parity-ethereum/blob/master/ethcore/src/state/mod.rs#L309, I have never think about `why should` or `why should not`

I understand your problem, I think thers are 2 easy ways to slove it:

- Use `pub fn new(db: &'db mut B)` like your suggestion
- Or, append a function like 

```rs
pub fn db(&self) -> &B {
    &self.db
}
```

**Comment by mohanson** [comment]
I will search parity's code tomorrow, It's really an interesting problem.

**Comment by mohanson** [comment]
Portal to some helpful codes in parity: 

https://github.com/paritytech/parity-ethereum/blob/master/ethcore/src/client/client.rs#L1036

https://github.com/paritytech/parity-ethereum/blob/master/util/journaldb/src/archivedb.rs#L117
