### ISSUE TITLE
more benchmarks of cita-vm

### ISSUE THREAD

**Issue by cdetrio** [cryptape/cita-vm#55]
We included cita-vm in our [EVM benchmarks here](https://github.com/ewasm/benchmarking/tree/055724568a6148d0d7e4a7ce28f2f5ff568099af). Take a look if you're curious!

**Comment by mohanson** [comment]
I think there is a place where the statement needs to be modified: cita-vm is not based on parity-vm, although we refer to go-ethereum and parity, but cita-vm is a independent project.

Thank you for your test.

**Comment by cdetrio** [comment]
Sorry about that, fixed!
