### ISSUE TITLE
你好，你的simplestorage.rs中的code是怎么生成的？我在remix生成的bytecode与你代码里的不一样

### ISSUE THREAD

**Issue by 60ke** [cryptape/cita-vm#74]
用remix编译例子中的simplestorage.sol得到的是
{
	"linkReferences": {},
	"object": "608060405234801561001057600080fd5b5060df8061001f6000396000f3006080604052600436106049576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806360fe47b114604e5780636d4ce63c146078575b600080fd5b348015605957600080fd5b5060766004803603810190808035906020019092919050505060a0565b005b348015608357600080fd5b50608a60aa565b6040518082815260200191505060405180910390f35b8060008190555050565b600080549050905600a165627a7a723058207bad182279efbf8da8f9f6e4eb463869678fd8ad7cc30f0ac08438505d279c540029",
	"opcodes": "PUSH1 0x80 PUSH1 0x40 MSTORE CALLVALUE DUP1 ISZERO PUSH2 0x10 JUMPI PUSH1 0x0 DUP1 REVERT JUMPDEST POP PUSH1 0xDF DUP1 PUSH2 0x1F PUSH1 0x0 CODECOPY PUSH1 0x0 RETURN STOP PUSH1 0x80 PUSH1 0x40 MSTORE PUSH1 0x4 CALLDATASIZE LT PUSH1 0x49 JUMPI PUSH1 0x0 CALLDATALOAD PUSH29 0x100000000000000000000000000000000000000000000000000000000 SWAP1 DIV PUSH4 0xFFFFFFFF AND DUP1 PUSH4 0x60FE47B1 EQ PUSH1 0x4E JUMPI DUP1 PUSH4 0x6D4CE63C EQ PUSH1 0x78 JUMPI JUMPDEST PUSH1 0x0 DUP1 REVERT JUMPDEST CALLVALUE DUP1 ISZERO PUSH1 0x59 JUMPI PUSH1 0x0 DUP1 REVERT JUMPDEST POP PUSH1 0x76 PUSH1 0x4 DUP1 CALLDATASIZE SUB DUP2 ADD SWAP1 DUP1 DUP1 CALLDATALOAD SWAP1 PUSH1 0x20 ADD SWAP1 SWAP3 SWAP2 SWAP1 POP POP POP PUSH1 0xA0 JUMP JUMPDEST STOP JUMPDEST CALLVALUE DUP1 ISZERO PUSH1 0x83 JUMPI PUSH1 0x0 DUP1 REVERT JUMPDEST POP PUSH1 0x8A PUSH1 0xAA JUMP JUMPDEST PUSH1 0x40 MLOAD DUP1 DUP3 DUP2 MSTORE PUSH1 0x20 ADD SWAP2 POP POP PUSH1 0x40 MLOAD DUP1 SWAP2 SUB SWAP1 RETURN JUMPDEST DUP1 PUSH1 0x0 DUP2 SWAP1 SSTORE POP POP JUMP JUMPDEST PUSH1 0x0 DUP1 SLOAD SWAP1 POP SWAP1 JUMP STOP LOG1 PUSH6 0x627A7A723058 KECCAK256 PUSH28 0xAD182279EFBF8DA8F9F6E4EB463869678FD8AD7CC30F0AC08438505D 0x27 SWAP13 SLOAD STOP 0x29 ",
	"sourceMap": "26:194:0:-;;;;8:9:-1;5:2;;;30:1;27;20:12;5:2;26:194:0;;;;;;;"
}

**Comment by 60ke** [comment]
> 不同版本的 solc 生成的字节码会有细微区别, 但通常功能上是等价的. 你可以尝试使用 remix 上的 v0.4.24 版本的 solc 来编译这段代码

感谢你的回复，不过我是用的v0.4.24 版本，然后将object对应的字段替换例子中的simplestorage.rs中的code的值。最后得到的结果是这样：
return=Normal([96, 128, 96, 64, 82, 52, 128, 21, 96, 15, 87, 96, 0, 128, 253, 91, 80, 96, 4, 54, 16, 96, 50, 87, 96, 0, 53, 96, 224, 28, 128, 99, 96, 254, 71, 177, 20, 96, 55, 87, 128, 99, 109, 76, 230, 60, 20, 96, 98, 87, 91, 96, 0, 128, 253, 91, 96, 96, 96, 4, 128, 54, 3, 96, 32, 129, 16, 21, 96, 75, 87, 96, 0, 128, 253, 91, 129, 1, 144, 128, 128, 53, 144, 96, 32, 1, 144, 146, 145, 144, 80, 80, 80, 96, 126, 86, 91, 0, 91, 96, 104, 96, 136, 86, 91, 96, 64, 81, 128, 130, 129, 82, 96, 32, 1, 145, 80, 80, 96, 64, 81, 128, 145, 3, 144, 243, 91, 128, 96, 0, 129, 144, 85, 80, 80, 86, 91, 96, 0, 128, 84, 144, 80, 144, 86, 254, 162, 101, 98, 122, 122, 114, 49, 88, 32, 228, 17, 153, 133, 43, 202, 192, 238, 83, 107, 145, 220, 153, 127, 140, 77, 141, 46, 143, 25, 187, 245, 237, 72, 30, 93, 122, 104, 160, 150, 50, 166, 100, 115, 111, 108, 99, 67, 0, 5, 11, 0, 50], 58443, [])
return=Normal([96, 128, 96, 64, 82, 52, 128, 21, 96, 15, 87, 96, 0, 128, 253, 91, 80, 96, 4, 54, 16, 96, 50, 87, 96, 0, 53, 96, 224, 28, 128, 99, 96, 254, 71, 177, 20, 96, 55, 87, 128, 99, 109, 76, 230, 60, 20, 96, 98, 87, 91, 96, 0, 128, 253, 91, 96, 96, 96, 4, 128, 54, 3, 96, 32, 129, 16, 21, 96, 75, 87, 96, 0, 128, 253, 91, 129, 1, 144, 128, 128, 53, 144, 96, 32, 1, 144, 146, 145, 144, 80, 80, 80, 96, 126, 86, 91, 0, 91, 96, 104, 96, 136, 86, 91, 96, 64, 81, 128, 130, 129, 82, 96, 32, 1, 145, 80, 80, 96, 64, 81, 128, 145, 3, 144, 243, 91, 128, 96, 0, 129, 144, 85, 80, 80, 86, 91, 96, 0, 128, 84, 144, 80, 144, 86, 254, 162, 101, 98, 122, 122, 114, 49, 88, 32, 228, 17, 153, 133, 43, 202, 192, 238, 83, 107, 145, 220, 153, 127, 140, 77, 141, 46, 143, 25, 187, 245, 237, 72, 30, 93, 122, 104, 160, 150, 50, 166, 100, 115, 111, 108, 99, 67, 0, 5, 11, 0, 50], 58635, [])
用了好几个版本的都试过了，除了用例子中的code值结果是正常的其它都不对，所以比较好奇您当时的code值是怎么生成的，我好再验证一下。

**Comment by mohanson** [comment]
非常抱歉! 在编写 examples 的时候, 我认为我当时并没有记录下被使用的 solc 的版本号.

**Comment by 60ke** [comment]
> 非常抱歉! 在编写 examples 的时候, 我认为我当时并没有记录下被使用的 solc 的版本号.
我也觉得”不同版本的 solc 生成的字节码会有细微区别, 但通常功能上是等价的. “ 而且你例子中的sol版本也标注的是v0.4.24。我觉得版本应该是没问题的，我想是不是不能将用”remix编译例子中的simplestorage.sol“的object字段直接替换code。您当时的code是用solc --bin SimpleStorage.sol得到的二进制直接放进code字段了，还是还有某些转换才行？给你添麻烦了，再次感谢！

**Comment by ouwenkg** [comment]
使用 `solc --bin SimpleStorage.sol` 每次编译得到的字节码也会有差别的．

**Comment by 60ke** [comment]
那我我用docker把所有版本的solc跑一遍

**Comment by 60ke** [comment]
> > 非常抱歉! 在编写 examples 的时候, 我认为我当时并没有记录下被使用的 solc 的版本号.
> > 我也觉得”不同版本的 solc 生成的字节码会有细微区别, 但通常功能上是等价的. “ 而且你例子中的sol版本也标注的是v0.4.24。我觉得版本应该是没问题的，我想是不是不能将用”remix编译例子中的simplestorage.sol“的object字段直接替换code。您当时的code是用solc --bin SimpleStorage.sol得到的二进制直接放进code字段了，还是还有某些转换才行？给你添麻烦了，再次感谢！

应该放runtime的bytecode，我放的是Creation Bytecode 尴尬

**Comment by leeyr338** [comment]
> 应该放runtime的bytecode，我放的是Creation Bytecode 尴尬

对，两者是有差别的。
